### ISSUE TITLE
Problem with api on cryptopia (SOLVED)

### ISSUE THREAD

**Issue by Cloniko** [Crypto-toolbox/bitex#154]
Hello,
i see a error on cryptopia. Dont work with api keys.

Code:
```python 
print('\nCRYPTOPIA --------------------------------------------------------------------------------')
print(Fore.LIGHTGREEN_EX + Cryptopair)

Cryptocfg = Cryptopia(config='%s/bitex/auth/cryptopia.ini' % '.')
Cryptoresp = Cryptocfg.order_book(Cryptopair)
CryptoAsk = Cryptoresp.json()['Data']['Buy'][0]['Price']
CryptoAskVolume = Cryptoresp.json()['Data']['Buy'][0]['Volume']
CryptoBuy = Cryptoresp.json()['Data']['Sell'][0]['Price']
CryptoBuyVolume = Cryptoresp.json()['Data']['Sell'][0]['Volume']

print('Venta en Cryptopia a %.8f ' % (CryptoAsk)+ ' Cantidad: ' + str(CryptoAskVolume))
print('Compra en Cryptopia a %.8f ' % (CryptoBuy) + ' Cantidad: ' + str(CryptoBuyVolume))

CryptoBalance = Cryptocfg.open_orders().json()
print('Balance BTC Cryptopia ' + str(CryptoBalance))

Cryptowall = Cryptocfg.wallet().json()
print('Cryptowall ' + str(Cryptowall))

Res:

CRYPTOPIA --------------------------------------------------------------------------------
BTC_DOGE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.cryptopia.co.nz
2018-01-18 03:54:17,156 - DEBUG - Starting new HTTPS connection (1): www.cryptopia.co.nz
DEBUG:urllib3.connectionpool:https://www.cryptopia.co.nz:443 "GET /api/GetTradePairs HTTP/1.1" 200 None
2018-01-18 03:54:17,984 - DEBUG - https://www.cryptopia.co.nz:443 "GET /api/GetTradePairs HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.cryptopia.co.nz
2018-01-18 03:54:24,444 - DEBUG - Starting new HTTPS connection (1): www.cryptopia.co.nz
DEBUG:urllib3.connectionpool:https://www.cryptopia.co.nz:443 "GET /api/GetMarketOrders/DOGE_BTC HTTP/1.1" 200
None
2018-01-18 03:54:25,283 - DEBUG - https://www.cryptopia.co.nz:443 "GET /api/GetMarketOrders/DOGE_BTC HTTP/1.1"
 200 None
Venta en Cryptopia a 0.00000071  Cantidad: 1875649.05537847
Compra en Cryptopia a 0.00000072  Cantidad: 8551.08496984
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.cryptopia.co.nz
2018-01-18 03:54:25,293 - DEBUG - Starting new HTTPS connection (1): www.cryptopia.co.nz
DEBUG:urllib3.connectionpool:https://www.cryptopia.co.nz:443 "POST /api/GetOpenOrders HTTP/1.1" 200 None
2018-01-18 03:54:25,929 - DEBUG - https://www.cryptopia.co.nz:443 "POST /api/GetOpenOrders HTTP/1.1" 200 None
Balance BTC Cryptopia {'Success': False, 'Error': 'Signature does not match request parameters.'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.cryptopia.co.nz
2018-01-18 03:54:25,934 - DEBUG - Starting new HTTPS connection (1): www.cryptopia.co.nz
DEBUG:urllib3.connectionpool:https://www.cryptopia.co.nz:443 "POST /api/GetBalance HTTP/1.1" 200 None
2018-01-18 03:54:26,607 - DEBUG - https://www.cryptopia.co.nz:443 "POST /api/GetBalance HTTP/1.1" 200 None
Cryptowall {'Success': False, 'Error': 'Signature does not match request parameters.'}
```

**Comment by nlsdfnbch** [comment]
I'll look into it!

**Comment by iuvbio** [comment]
Hi,

I still have issues with the Cryptopia API also with the balance method. The error message is:
```python
DEBUG:bitex.api.REST.api:Making request to: https://www.cryptopia.co.nz/api/GetBalance, kwargs: {'headers': {'Authorization': ' ', 'Content-Type': 'application/json; charset=utf-8'}, 'data': '{}'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.cryptopia.co.nz
DEBUG:urllib3.connectionpool:https://www.cryptopia.co.nz:443 "POST /api/GetBalance HTTP/1.1" 401 0
DEBUG:bitex.api.REST.api:Made POST request made to https://www.cryptopia.co.nz/api/GetBalance, with headers {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': ' ', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '2'} and body {}. Status code 401
ERROR:bitex.utils:return_api_response: HTTPError for url https://www.cryptopia.co.nz/api/GetBalance
Traceback (most recent call last):
  File "/home/usr/bin/anaconda3/lib/python3.6/site-packages/bitex/utils.py", line 40, in wrapper
    r.raise_for_status()
  File "/home/usr/bin/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.cryptopia.co.nz/api/GetBalance
ERROR:bitex.utils:return_api_response(): Unexpected error while parsing json from https://www.cryptopia.co.nz/api/GetBalance
```

**Comment by nlsdfnbch** [comment]
@iuvbio , thanks for the feedback - are you using the latest release or the `dev` branch (`2.0.0x`) ?

**Comment by iuvbio** [comment]
My initial comment was using the master, in issue #168 I use the `dev` branch and I get the same error as the OP `Signature does not match request parameters`

**Comment by iuvbio** [comment]
I found the issue, in the Cryptopia REST API `sign_request_kwargs()` change
```Python
hmac_sig = base64.b64encode(hmac.new(base64.b64decode(self.secret),
                                             signature.encode('utf-8'),
                                             hashlib.sha256).digest())
```

**Comment by nlsdfnbch** [comment]
I'll check this later today - thanks for your help!

**Comment by iuvbio** [comment]
You're welcome. Actually it works as is on the `dev` branch, I was still using the master.

**Comment by Cloniko** [comment]
Yes!!. Work fine now. Solved!!
